### ISSUE TITLE
Does it use BERT to generate a sequence of x_0?

### ISSUE THREAD

**Issue by greens007** [EBGU/Diffusion-LM#1]

**Comment by EBGU** [comment]
No. It uses BERT to initialize weights. Finetuning could be much easier than train from scratch.

**Comment by greens007** [comment]
> No. It uses BERT to initialize weights. Finetuning could be much easier than train from scratch.

Thanks. I have seen their original code, but I found that your code just duplicated their token_discrete_loss, without the diffusion loss (mse loss). Right?
![image](https://user-images.githubusercontent.com/66548783/195324926-a944aedc-b245-43b8-96d6-abc2bfd014e5.png)
![image](https://user-images.githubusercontent.com/66548783/195324977-37f304dd-1c6f-4fd3-9bcf-34811d8390d6.png)
